name: Build and deploy documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: nixos
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/cachix-action@v15
        with:
          name: paolino
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build docs
        run: nix develop github:paolino/dev-assets?dir=mkdocs --quiet -c mkdocs build --strict
      - name: Deploy docs
        if: github.ref == 'refs/heads/main'
        run: nix develop github:paolino/dev-assets?dir=mkdocs --quiet -c mkdocs gh-deploy --force
